//! Embedded web management panel for CandyTunnel.
//!
//! A self-contained HTTP/1.1 server (hand-rolled over `async-net`, no extra web
//! framework) that serves a single-page, bilingual (Persian/English) admin UI
//! and a small JSON API. It manages CandyTunnel instances the same way
//! `candy-manager.sh` does — reading/writing `/etc/candytunnel/*.toml`, driving
//! `systemctl`, tailing `journalctl`, and launching the spoofed-IP tester.
//!
//! Security model:
//!   * Binds `127.0.0.1` by default — expose it only behind SSH/TLS.
//!   * Password login required; 256-bit opaque session tokens in an
//!     HttpOnly, SameSite=Strict cookie.
//!   * Mutating requests must carry an `X-CandyTunnel` header (the SPA sets it),
//!     which together with SameSite=Strict defeats CSRF.
//!   * Login attempts are rate-limited per source IP.
//!   * Instance names are strictly validated; no user input ever reaches a
//!     shell (commands run via argv, never `sh -c`).

mod auth;
mod instances;
mod iptest;
mod sysinfo;

use std::collections::HashMap;
use std::net::{IpAddr, SocketAddr};
use std::sync::Arc;
use std::time::Duration;

use anyhow::{bail, Context, Result};
use async_net::{TcpListener, TcpStream};
use futures_lite::io::{AsyncReadExt, AsyncWriteExt};
use serde::Deserialize;
use serde_json::{json, Value};

use auth::Sessions;
use iptest::JobStore;

const SESSION_COOKIE: &str = "ct_session";
const MAX_HEADER_BYTES: usize = 32 * 1024;
const MAX_BODY_BYTES: usize = 2 * 1024 * 1024;
const UI_HTML: &str = include_str!("ui.html");

// ── Panel configuration ─────────────────────────────────────────────────────

/// Options passed from the CLI to [`run_panel`].
#[derive(Debug, Clone)]
pub struct PanelOptions {
    /// Path to the panel's own TOML config.
    pub config_path: String,
    /// Optional CLI override for the bind address.
    pub bind_override: Option<String>,
    /// Optional CLI-supplied password (hashed in-memory for this run only).
    pub password_override: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
struct PanelConfigFile {
    #[serde(default = "default_bind")]
    bind: String,
    #[serde(default)]
    password_hash: String,
    #[serde(default)]
    password_salt: String,
    /// Optional plaintext password (discouraged; prefer `--set-password`).
    #[serde(default)]
    password: String,
    #[serde(default = "default_ttl")]
    session_ttl_secs: u64,
    #[serde(default = "default_config_dir")]
    config_dir: String,
    #[serde(default = "default_bin_path")]
    bin_path: String,
    #[serde(default = "default_service_prefix")]
    service_prefix: String,
}

fn default_bind() -> String { "127.0.0.1:8088".to_string() }
fn default_ttl() -> u64 { 3600 }
fn default_config_dir() -> String { "/etc/candytunnel".to_string() }
fn default_bin_path() -> String { "/opt/candytunnel/candy-tunnel".to_string() }
fn default_service_prefix() -> String { "candytunnel".to_string() }

/// Resolved, runtime panel configuration.
struct PanelConfig {
    password_hash: String,
    password_salt: String,
    session_ttl: Duration,
    config_dir: String,
    bin_path: String,
    service_prefix: String,
}

/// Shared server state.
struct PanelState {
    cfg: PanelConfig,
    sessions: Sessions,
    jobs: JobStore,
}

// ── Entry points ─────────────────────────────────────────────────────────────

/// Interactively set the panel password and persist its salted hash into the
/// panel config file, then return. Used by `candy-tunnel panel --set-password`.
pub fn set_password(config_path: &str) -> Result<()> {
    let pw1 = rpassword::prompt_password("New panel password: ")?;
    if pw1.len() < 6 {
        bail!("password must be at least 6 characters");
    }
    let pw2 = rpassword::prompt_password("Confirm panel password: ")?;
    if pw1 != pw2 {
        bail!("passwords do not match");
    }

    let salt = auth::random_salt();
    let hash = auth::hash_password(&salt, &pw1);

    // Preserve any existing non-secret settings; rewrite the file.
    let existing: PanelConfigFile = std::fs::read_to_string(config_path)
        .ok()
        .and_then(|s| toml::from_str(&s).ok())
        .unwrap_or_else(|| toml::from_str("").expect("empty config parses with defaults"));

    if let Some(dir) = std::path::Path::new(config_path).parent() {
        let _ = std::fs::create_dir_all(dir);
    }

    let contents = format!(
        "# CandyTunnel web panel configuration\n\
         # Generated by `candy-tunnel panel --set-password`\n\n\
         bind           = \"{bind}\"\n\
         session_ttl_secs = {ttl}\n\
         config_dir     = \"{config_dir}\"\n\
         bin_path       = \"{bin_path}\"\n\
         service_prefix = \"{prefix}\"\n\n\
         # Salted SHA-256 of the panel password. Do not edit by hand.\n\
         password_salt  = \"{salt}\"\n\
         password_hash  = \"{hash}\"\n",
        bind = existing.bind,
        ttl = existing.session_ttl_secs,
        config_dir = existing.config_dir,
        bin_path = existing.bin_path,
        prefix = existing.service_prefix,
        salt = salt,
        hash = hash,
    );
    std::fs::write(config_path, contents)
        .with_context(|| format!("write {}", config_path))?;

    // Best-effort: restrict the file to root since it holds the password hash.
    #[cfg(target_os = "linux")]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(config_path, std::fs::Permissions::from_mode(0o600));
    }

    println!("Panel password updated: {}", config_path);
    Ok(())
}

/// Run the web panel. Never returns unless the listener fails.
pub async fn run_panel(opts: PanelOptions) -> Result<()> {
    let file: PanelConfigFile = match std::fs::read_to_string(&opts.config_path) {
        Ok(s) => toml::from_str(&s)
            .with_context(|| format!("invalid panel config {}", opts.config_path))?,
        Err(_) => {
            log::warn!(
                "panel config {} not found — using defaults",
                opts.config_path
            );
            toml::from_str("").expect("empty config parses with defaults")
        }
    };

    // Resolve the password: CLI override wins, then stored hash, then plaintext.
    let (password_hash, password_salt) = if let Some(pw) = &opts.password_override {
        let salt = auth::random_salt();
        (auth::hash_password(&salt, pw), salt)
    } else if !file.password_hash.is_empty() && !file.password_salt.is_empty() {
        (file.password_hash.clone(), file.password_salt.clone())
    } else if !file.password.is_empty() {
        log::warn!("panel: using plaintext `password` from config — prefer `--set-password`");
        let salt = auth::random_salt();
        (auth::hash_password(&salt, &file.password), salt)
    } else {
        bail!(
            "no panel password configured. Run:\n    candy-tunnel panel --config {} --set-password",
            opts.config_path
        );
    };

    let bind = opts.bind_override.clone().unwrap_or_else(|| file.bind.clone());

    let cfg = PanelConfig {
        password_hash,
        password_salt,
        session_ttl: Duration::from_secs(file.session_ttl_secs.max(60)),
        config_dir: file.config_dir.clone(),
        bin_path: file.bin_path.clone(),
        service_prefix: file.service_prefix.clone(),
    };

    let state = Arc::new(PanelState {
        sessions: Sessions::new(cfg.session_ttl),
        jobs: JobStore::new(),
        cfg,
    });

    let listener = TcpListener::bind(&bind)
        .await
        .with_context(|| format!("bind panel on {}", bind))?;

    log::info!("CandyTunnel panel listening on http://{}", bind);
    if !bind.starts_with("127.") && !bind.starts_with("localhost") {
        log::warn!(
            "panel bound to a non-loopback address ({}) — ensure it is firewalled or behind TLS",
            bind
        );
    }

    loop {
        let (stream, peer) = match listener.accept().await {
            Ok(v) => v,
            Err(e) => {
                log::warn!("panel accept: {}", e);
                continue;
            }
        };
        let state = state.clone();
        // Each connection is one request/response (Connection: close).
        tokio::spawn(async move {
            if let Err(e) = serve_connection(state, stream, peer).await {
                log::trace!("panel conn [{}]: {}", peer, e);
            }
        });
    }
}

// ── HTTP request/response plumbing ────────────────────────────────────────────

struct Request {
    method: String,
    path: String,
    query: HashMap<String, String>,
    headers: Vec<(String, String)>,
    body: Vec<u8>,
    peer: IpAddr,
}

impl Request {
    fn header(&self, name: &str) -> Option<&str> {
        let name = name.to_ascii_lowercase();
        self.headers
            .iter()
            .find(|(k, _)| *k == name)
            .map(|(_, v)| v.as_str())
    }

    fn cookie(&self, key: &str) -> Option<String> {
        let raw = self.header("cookie")?;
        for part in raw.split(';') {
            let part = part.trim();
            if let Some(rest) = part.strip_prefix(key) {
                if let Some(val) = rest.strip_prefix('=') {
                    return Some(val.to_string());
                }
            }
        }
        None
    }

    fn json<T: serde::de::DeserializeOwned>(&self) -> Result<T> {
        serde_json::from_slice(&self.body).context("invalid JSON body")
    }
}

struct Response {
    status: u16,
    content_type: String,
    body: Vec<u8>,
    extra_headers: Vec<(String, String)>,
}

impl Response {
    fn new(status: u16, content_type: &str, body: Vec<u8>) -> Self {
        Self {
            status,
            content_type: content_type.to_string(),
            body,
            extra_headers: Vec::new(),
        }
    }

    fn json(status: u16, value: Value) -> Self {
        Self::new(status, "application/json; charset=utf-8", value.to_string().into_bytes())
    }

    fn html(body: &str) -> Self {
        Self::new(200, "text/html; charset=utf-8", body.as_bytes().to_vec())
    }

    fn with_header(mut self, k: &str, v: &str) -> Self {
        self.extra_headers.push((k.to_string(), v.to_string()));
        self
    }

    fn status_text(status: u16) -> &'static str {
        match status {
            200 => "OK",
            204 => "No Content",
            400 => "Bad Request",
            401 => "Unauthorized",
            403 => "Forbidden",
            404 => "Not Found",
            405 => "Method Not Allowed",
            409 => "Conflict",
            429 => "Too Many Requests",
            500 => "Internal Server Error",
            _ => "OK",
        }
    }
}

async fn serve_connection(
    state: Arc<PanelState>,
    mut stream: TcpStream,
    peer: SocketAddr,
) -> Result<()> {
    let req = match read_request(&mut stream, peer.ip()).await? {
        Some(r) => r,
        None => return Ok(()), // empty/closed connection
    };
    let resp = route(&state, &req).await;
    write_response(&mut stream, &resp).await?;
    let _ = stream.flush().await;
    Ok(())
}

async fn read_request(stream: &mut TcpStream, peer: IpAddr) -> Result<Option<Request>> {
    let mut buf: Vec<u8> = Vec::with_capacity(4096);
    let mut tmp = [0u8; 4096];
    let header_end;

    loop {
        let n = stream.read(&mut tmp).await?;
        if n == 0 {
            if buf.is_empty() {
                return Ok(None);
            }
            bail!("connection closed before headers complete");
        }
        buf.extend_from_slice(&tmp[..n]);
        if let Some(pos) = find_subslice(&buf, b"\r\n\r\n") {
            header_end = pos + 4;
            break;
        }
        if buf.len() > MAX_HEADER_BYTES {
            bail!("request headers too large");
        }
    }

    let header_text = String::from_utf8_lossy(&buf[..header_end]).to_string();
    let mut lines = header_text.split("\r\n");
    let request_line = lines.next().unwrap_or("");
    let mut parts = request_line.split_whitespace();
    let method = parts.next().unwrap_or("").to_string();
    let target = parts.next().unwrap_or("/").to_string();

    let (path, query) = parse_target(&target);

    let mut headers = Vec::new();
    for line in lines {
        if line.is_empty() {
            continue;
        }
        if let Some((k, v)) = line.split_once(':') {
            headers.push((k.trim().to_ascii_lowercase(), v.trim().to_string()));
        }
    }

    let content_length = headers
        .iter()
        .find(|(k, _)| k == "content-length")
        .and_then(|(_, v)| v.parse::<usize>().ok())
        .unwrap_or(0);

    if content_length > MAX_BODY_BYTES {
        bail!("request body too large");
    }

    let mut body = buf[header_end..].to_vec();
    while body.len() < content_length {
        let n = stream.read(&mut tmp).await?;
        if n == 0 {
            break;
        }
        body.extend_from_slice(&tmp[..n]);
        if body.len() > MAX_BODY_BYTES {
            bail!("request body too large");
        }
    }
    body.truncate(content_length);

    Ok(Some(Request {
        method,
        path,
        query,
        headers,
        body,
        peer,
    }))
}

fn parse_target(target: &str) -> (String, HashMap<String, String>) {
    let mut query = HashMap::new();
    let (path, qs) = match target.split_once('?') {
        Some((p, q)) => (p.to_string(), q),
        None => (target.to_string(), ""),
    };
    for pair in qs.split('&') {
        if pair.is_empty() {
            continue;
        }
        let (k, v) = pair.split_once('=').unwrap_or((pair, ""));
        query.insert(url_decode(k), url_decode(v));
    }
    (path, query)
}

fn url_decode(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'%' if i + 2 < bytes.len() => {
                let h = hex_val(bytes[i + 1]);
                let l = hex_val(bytes[i + 2]);
                if let (Some(h), Some(l)) = (h, l) {
                    out.push(h << 4 | l);
                    i += 3;
                    continue;
                }
                out.push(bytes[i]);
                i += 1;
            }
            b'+' => {
                out.push(b' ');
                i += 1;
            }
            b => {
                out.push(b);
                i += 1;
            }
        }
    }
    String::from_utf8_lossy(&out).into_owned()
}

fn hex_val(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        b'A'..=b'F' => Some(b - b'A' + 10),
        _ => None,
    }
}

fn find_subslice(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    if needle.is_empty() || haystack.len() < needle.len() {
        return None;
    }
    haystack
        .windows(needle.len())
        .position(|w| w == needle)
}

async fn write_response(stream: &mut TcpStream, resp: &Response) -> Result<()> {
    let mut head = format!(
        "HTTP/1.1 {} {}\r\n\
         Content-Type: {}\r\n\
         Content-Length: {}\r\n\
         Connection: close\r\n\
         X-Content-Type-Options: nosniff\r\n\
         Cache-Control: no-store\r\n",
        resp.status,
        Response::status_text(resp.status),
        resp.content_type,
        resp.body.len(),
    );
    for (k, v) in &resp.extra_headers {
        head.push_str(&format!("{}: {}\r\n", k, v));
    }
    head.push_str("\r\n");
    stream.write_all(head.as_bytes()).await?;
    stream.write_all(&resp.body).await?;
    Ok(())
}

// ── Routing ───────────────────────────────────────────────────────────────────

fn is_authed(state: &PanelState, req: &Request) -> bool {
    match req.cookie(SESSION_COOKIE) {
        Some(tok) => state.sessions.validate(&tok),
        None => false,
    }
}

async fn route(state: &Arc<PanelState>, req: &Request) -> Response {
    let path = req.path.clone();

    // Static UI + favicon.
    if req.method == "GET" && (path == "/" || !path.starts_with("/api")) {
        if path == "/favicon.ico" {
            return Response::new(204, "image/x-icon", Vec::new());
        }
        return Response::html(UI_HTML);
    }

    // Public API endpoints.
    match (req.method.as_str(), path.as_str()) {
        ("POST", "/api/login") => return handle_login(state, req),
        ("GET", "/api/session") => {
            return Response::json(200, json!({ "authenticated": is_authed(state, req) }));
        }
        _ => {}
    }

    // Everything else requires a valid session.
    if !is_authed(state, req) {
        return Response::json(401, json!({ "error": "authentication required" }));
    }

    // CSRF guard for mutating requests.
    if matches!(req.method.as_str(), "POST" | "DELETE" | "PUT")
        && req.header("x-candytunnel").is_none()
    {
        return Response::json(403, json!({ "error": "missing X-CandyTunnel header" }));
    }

    state.sessions.sweep();

    let segs: Vec<&str> = path.trim_matches('/').split('/').collect();
    match (req.method.as_str(), segs.as_slice()) {
        ("POST", ["api", "logout"]) => {
            if let Some(tok) = req.cookie(SESSION_COOKIE) {
                state.sessions.revoke(&tok);
            }
            Response::json(200, json!({ "ok": true }))
        }
        ("GET", ["api", "system"]) => Response::json(200, serde_json::to_value(sysinfo::collect()).unwrap()),
        ("GET", ["api", "protocols"]) => Response::json(
            200,
            json!({
                "protocols": ["udp", "icmp", "proto58", "tcp", "quic", "ipip", "gre"],
                "perf_modes": ["throughput", "latency", "balanced"],
                "log_levels": ["error", "warn", "info", "debug", "trace"],
                "roles": ["client", "server"],
            }),
        ),
        ("GET", ["api", "instances"]) => instances::list(state).await,
        ("POST", ["api", "instances"]) => instances::create_or_update(state, req).await,
        ("GET", ["api", "instances", name]) => instances::get(state, name).await,
        ("DELETE", ["api", "instances", name]) => instances::remove(state, name).await,
        ("POST", ["api", "instances", name, "action"]) => instances::action(state, req, name).await,
        ("GET", ["api", "instances", name, "logs"]) => instances::logs(state, req, name).await,
        ("POST", ["api", "iptest"]) => iptest::start(state, req).await,
        ("GET", ["api", "iptest", id]) => iptest::status(state, id),
        _ => Response::json(404, json!({ "error": "not found" })),
    }
}

#[derive(Deserialize)]
struct LoginReq {
    password: String,
}

fn handle_login(state: &Arc<PanelState>, req: &Request) -> Response {
    if state.sessions.is_locked(req.peer) {
        return Response::json(429, json!({ "error": "too many attempts, try again later" }));
    }
    let body: LoginReq = match req.json() {
        Ok(b) => b,
        Err(_) => return Response::json(400, json!({ "error": "bad request" })),
    };
    let candidate = auth::hash_password(&state.cfg.password_salt, &body.password);
    if auth::constant_time_eq(&candidate, &state.cfg.password_hash) {
        state.sessions.record_success(req.peer);
        let token = state.sessions.create();
        let ttl = state.cfg.session_ttl.as_secs();
        let cookie = format!(
            "{}={}; HttpOnly; SameSite=Strict; Path=/; Max-Age={}",
            SESSION_COOKIE, token, ttl
        );
        Response::json(200, json!({ "ok": true })).with_header("Set-Cookie", &cookie)
    } else {
        state.sessions.record_failure(req.peer);
        Response::json(401, json!({ "error": "invalid password" }))
    }
}

// ── Shared command helper ──────────────────────────────────────────────────────

/// Run an external command (never via a shell) on a blocking thread.
/// Returns (success, stdout, stderr).
pub(super) async fn run_cmd(program: &str, args: Vec<String>) -> (bool, String, String) {
    let program = program.to_string();
    let result = tokio::task::spawn_blocking(move || {
        std::process::Command::new(&program).args(&args).output()
    })
    .await;

    match result {
        Ok(Ok(out)) => (
            out.status.success(),
            String::from_utf8_lossy(&out.stdout).into_owned(),
            String::from_utf8_lossy(&out.stderr).into_owned(),
        ),
        Ok(Err(e)) => (false, String::new(), e.to_string()),
        Err(e) => (false, String::new(), e.to_string()),
    }
}

/// Validate an instance name: alphanumeric, dash, underscore, 1–32 chars.
pub(super) fn valid_instance_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= 32
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}
