#!/usr/bin/env bash
#
# CandyTunnel — one-line panel installer.
#
#   bash <(curl -fsSL https://raw.githubusercontent.com/MAHDI-byte64/spoof/main/scripts/install.sh)
#
# Downloads the latest release binary, installs the web panel as a systemd
# service, sets a login password, and prints the URL. Tunnels themselves are
# then created and managed from the panel.
#
# Optional environment overrides:
#   PANEL_PORT=8088         port the panel listens on   (default: random high port)
#   PANEL_BIND=0.0.0.0      address the panel binds to  (default: 0.0.0.0)
#   PANEL_PASS=...          login password              (default: prompt, else random)
#   CT_VERSION=v4.2.0       release tag to install      (default: latest)

set -euo pipefail

RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'; CYAN=$'\033[0;36m'; BOLD=$'\033[1m'; NC=$'\033[0m'
info(){ echo "${CYAN}[*]${NC} $*"; }
ok(){   echo "${GREEN}[✓]${NC} $*"; }
warn(){ echo "${YELLOW}[!]${NC} $*"; }
die(){  echo "${RED}[x]${NC} $*" >&2; exit 1; }

REPO="MAHDI-byte64/spoof"
INSTALL_DIR="/opt/candytunnel"
CONFIG_DIR="/etc/candytunnel"
BIN_PATH="${INSTALL_DIR}/candy-tunnel"
PANEL_CONFIG="${CONFIG_DIR}/panel.toml"
PANEL_SERVICE="candytunnel-panel.service"
SYSTEMD_DIR="/etc/systemd/system"

echo
echo "${BOLD}${CYAN}  CandyTunnel panel installer${NC}"
echo "  ─────────────────────────────"
echo

[ "$(id -u)" -eq 0 ] || die "please run as root (sudo)."

for dep in curl systemctl; do command -v "$dep" >/dev/null 2>&1 || die "missing dependency: $dep"; done

# ── Architecture ─────────────────────────────────────────────────────────────
case "$(uname -m)" in
  x86_64|amd64) ARCH="x86_64" ;;
  *) die "unsupported architecture $(uname -m) — only x86_64 release binaries are published. Build from source instead." ;;
esac

# ── Resolve the release asset ────────────────────────────────────────────────
API="https://api.github.com/repos/${REPO}/releases"
TAG="${CT_VERSION:-}"
if [ -z "$TAG" ]; then
  info "Finding the latest release…"
  TAG=$(curl -fsSL "${API}/latest" 2>/dev/null | grep -oE '"tag_name"[^,]*' | head -1 | sed -E 's/.*"tag_name" *: *"([^"]+)".*/\1/')
  [ -n "$TAG" ] || TAG=$(curl -fsSL "$API" 2>/dev/null | grep -oE '"tag_name"[^,]*' | head -1 | sed -E 's/.*"tag_name" *: *"([^"]+)".*/\1/')
fi
[ -n "$TAG" ] || die "could not reach the GitHub release API. Set CT_VERSION=vX.Y.Z and retry."
info "Release: ${BOLD}${TAG}${NC}"

ASSET="CandyTunnel-linux-${ARCH}"
URL="https://github.com/${REPO}/releases/download/${TAG}/${ASSET}"

# ── Download & install the binary ────────────────────────────────────────────
info "Downloading ${ASSET}…"
mkdir -p "$INSTALL_DIR" "$CONFIG_DIR"
TMP=$(mktemp)
curl -fL --progress-bar -o "$TMP" "$URL" || die "download failed: $URL"
chmod +x "$TMP"
"$TMP" --help >/dev/null 2>&1 || warn "the downloaded binary did not respond to --help; continuing anyway."
mv "$TMP" "$BIN_PATH"
ln -sf "$BIN_PATH" /usr/local/bin/candy-tunnel 2>/dev/null || true
echo "$TAG" > "${INSTALL_DIR}/VERSION"
ok "Binary installed: ${BOLD}${BIN_PATH}${NC}"

# ── Panel settings ───────────────────────────────────────────────────────────
BIND_ADDR="${PANEL_BIND:-0.0.0.0}"
if [ -n "${PANEL_PORT:-}" ]; then
  PORT="$PANEL_PORT"
elif [ -n "${PANEL_BIND:-}" ] && [[ "$PANEL_BIND" == *:* ]]; then
  PORT="${PANEL_BIND##*:}"; BIND_ADDR="${PANEL_BIND%:*}"
else
  PORT=$(( (RANDOM % 40000) + 20000 ))
fi
BIND="${BIND_ADDR}:${PORT}"

# Password: env, then a prompt on the terminal, else a strong random one.
PASS="${PANEL_PASS:-}"
GENERATED=0
if [ -z "$PASS" ]; then
  if [ -r /dev/tty ]; then
    printf "  %sSet a panel password%s (leave empty to auto-generate): " "$BOLD" "$NC" > /dev/tty
    read -rs PASS < /dev/tty || true; echo > /dev/tty
  fi
fi
if [ -z "$PASS" ]; then
  PASS=$(head -c 18 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 16)
  GENERATED=1
fi
[ "${#PASS}" -ge 6 ] || die "password must be at least 6 characters."

# ── Write the panel config ───────────────────────────────────────────────────
cat > "$PANEL_CONFIG" <<CFG
# CandyTunnel web panel — generated by install.sh
bind             = "${BIND}"
session_ttl_secs = 3600
config_dir       = "${CONFIG_DIR}"
bin_path         = "${BIN_PATH}"
service_prefix   = "candytunnel"
CFG
chmod 600 "$PANEL_CONFIG"
"$BIN_PATH" panel --config "$PANEL_CONFIG" --set-password --password "$PASS" >/dev/null
ok "Panel configured on ${BOLD}${BIND}${NC}"

# ── systemd service ──────────────────────────────────────────────────────────
cat > "${SYSTEMD_DIR}/${PANEL_SERVICE}" <<UNIT
[Unit]
Description=CandyTunnel Web Panel
Documentation=https://github.com/${REPO}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
ExecStart=${BIN_PATH} panel --config ${PANEL_CONFIG}
Restart=on-failure
RestartSec=5
AmbientCapabilities=CAP_NET_RAW CAP_NET_ADMIN
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
UNIT
systemctl daemon-reload
systemctl enable "$PANEL_SERVICE" >/dev/null 2>&1 || true
systemctl restart "$PANEL_SERVICE"
sleep 1

if ! systemctl is-active --quiet "$PANEL_SERVICE"; then
  warn "panel service failed to start. Recent logs:"
  journalctl -u "$PANEL_SERVICE" -n 20 --no-pager || true
  die "see the logs above."
fi

# ── Done ─────────────────────────────────────────────────────────────────────
PUBIP=$(curl -fsSL --max-time 4 https://api.ipify.org 2>/dev/null || true)
[ -n "$PUBIP" ] || PUBIP="<server-ip>"
echo
ok "CandyTunnel panel is running."
echo
if [[ "$BIND_ADDR" == 127.* || "$BIND_ADDR" == localhost ]]; then
  echo "  ${BOLD}Local only.${NC} Reach it over SSH:"
  echo "    ssh -L ${PORT}:${BIND} user@${PUBIP}"
  echo "  then open ${BOLD}http://127.0.0.1:${PORT}${NC}"
else
  echo "  ${BOLD}URL:${NC}      http://${PUBIP}:${PORT}"
fi
if [ "$GENERATED" -eq 1 ]; then
  echo "  ${BOLD}Password:${NC} ${GREEN}${PASS}${NC}   ${YELLOW}(save it now — it is not shown again)${NC}"
else
  echo "  ${BOLD}Password:${NC} (the one you set)"
fi
echo
echo "  Manage the service:  systemctl {status|restart|stop} ${PANEL_SERVICE}"
echo "  Change the password: candy-tunnel panel --config ${PANEL_CONFIG} --set-password"
echo
if [[ "$BIND_ADDR" != 127.* && "$BIND_ADDR" != localhost ]]; then
  warn "The panel is reachable from the internet. It is password-protected, but"
  warn "consider a firewall rule limiting port ${PORT} to your own IP."
fi
